services:
  db:
    image: postgres:15
    container_name: smartlife_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: smartlife_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: python bot.py

volumes:
  postgres_data:
